### PR TITLE
added advisor's profile

### PR DESCRIPTION
**Pull request by srija-ieee**

### CODE REVIEW

**Comment by obonac** [comment]
The formatting is lost in https://inoculum9.github.io/advisors/ compared to https://gsfvikram.github.io/advisors/

**Comment by srija-ieee** [comment]
added files from obonac

**Comment by srija-ieee** [comment]
> The formatting is lost in https://inoculum9.github.io/advisors/ compared to https://gsfvikram.github.io/advisors/

this has been fixed in the current version

**Comment by obonac** [comment]
Looks fine. Thank you

**Pull request merged**
